### ISSUE TITLE
5.2.86 published for Scala 2.10 but not 2.11

### ISSUE THREAD

**Issue by ceedubs** [oncue/funnel#30]
https://bintray.com/oncue/releases/funnel#files/oncue/funnel/core_2.11

**Comment by ceedubs** [comment]
Looks like it also doesn't have a git tag.

**Comment by neigor** [comment]
builds failed: https://travis-ci.org/oncue/funnel/builds/108341734
but i do not understand why. any ideas?

**Comment by ceedubs** [comment]
This seems to be resolved.
